name: React native build and deploy

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install
      working-directory: frontend-native

  trigger_appflow_android:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Appflow Build for Android
      uses: ionic-team/appflow-build@v1
      with:
        app-id: ${{ secrets.APPFLOW_APP_ID }}
        token: ${{ secrets.APPFLOW_TOKEN }}
        platform: Android
        build-type: debug
        environment: MyEnvironment
        upload-artifact: Android-Build.zip

  trigger_appflow_ios:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Appflow Build for iOS
      uses: ionic-team/appflow-build@v1
      with:
        app-id: ${{ secrets.APPFLOW_APP_ID }}
        token: ${{ secrets.APPFLOW_TOKEN }}
        platform: iOS
        build-type: ad-hoc
        certificate: MyCertificate
        environment: MyEnvironment
        upload-artifact: iOS-Build.zip
